name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps (web)
        run: pnpm install --filter apps/web...
      - name: Lint (web)
        working-directory: apps/web
        run: pnpm lint
      - name: Test (web)
        working-directory: apps/web
        run: pnpm test

  build_web:
    runs-on: ubuntu-latest
    needs: lint_web
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps (web)
        run: pnpm install --filter apps/web...
      - name: Build (web)
        working-directory: apps/web
        run: pnpm build

  build_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps (api)
        run: pnpm install --filter apps/api...
      - name: Build (api)
        working-directory: apps/api
        run: pnpm build
